# Site
repository: stephen-a-nicholson/stephen-a-nicholson.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Stephen Nicholson
title: Software and Data Engineer
email: stephen.nicholson1@hotmail.co.uk
website: stephen-a-nicholson.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: stephen-a-nicholson
linkedin_username: stephen-nicholson

about_title: About Me
# about_profile_image: images/profile.jpg
about_content: |
  I am a software and data engineer with experience in building pipelines that deliver high-quality data to people, applications, and machine learning models. I am enthusiastic about collaborating with agile teams to solve complex business problems with technology and am a proponent of DevOps practices that allow developers to rapidly experiment and deliver new features to customers. Effective communications skills with the capacity to tailor my approach to speak to non-technical stakeholders to understand business requirements and build strong relationships.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: NatWest Group (Edinburgh, UK)
        link: www.natwestgroup.com
        sub_title: Machine Learning Engineer
        caption: 2022 - present
        quote: Machine Learning Operations Team
        description: | 
          Working in the machine learning operations team.
      - layout: left
        title: NatWest Group (Edinburgh, UK)
        link: www.natwestgroup.com
        sub_title: Data Engineer
        caption: 2020 - 2022
        quote: Data Science and Innovation Team
        description: | 
          I built pipelines that write data to a new graph database solution to help analysts detect fraud. Explored the use of community detection and centrality algorithms on the graph. Worked closely with data scientists to define features for machine learning models. Built pipelines to deliver these features for model training and inference. Developed several Python packages to increase the productivity of engineers in NatWest. Delivered company-wide training and workshops on data science and engineering tools.
      - layout: left
        title: Momenta Group Global (Glasgow, UK)
        link: https://momentagroup.com/
        sub_title: Graduate Automation Engineer
        caption: 2020-2020
        quote: Working as an RPA developer for a big four company
        description: |
          Worked as a contractor for a Big Four company to provide support for 30+ RPA bots across several clients. Consulted with clients to understand the requirements of their RPA bots. Performed investigations to resolve incidents and implemented changes when required. Wrote high-quality documentation for RPA bots including Solution Design Documents, Test Plans, and Change requests. Developed an application to automate MI reporting, saving time for engineers to focus on more creative work.
      - layout: left
        title: Scottish Government (Edinburgh, UK)
        link: https://www.gov.scot/
        sub_title: Data Scientist
        caption: 2019 - 2019
        quote: Working in the office of the chief economic adviser
        description: |
          Efficiently worked in the Office of Chief Economic Advisor (OCEA) in the National Accounts Division. Processed, analysed, and presented complex data sets using advanced querying, visualisation, and analytics tools. Used predictive data modelling to contribute to the Sub-Scotland Productivity Model and the understanding of the Scottish economy. Introduced a new way of working to manipulate and evaluate data. Facilitated company transition for using the R programming language instead of SAS software. Supported economists in understanding R to save the government millions of pounds from the licence cost of the SAS software.

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Stirling
        caption: 2018 - 2019
        sub_title: MSc Big Data
        description: |
          Coursework: Mathematical Foundations, Statistics for Data Science, Representing & Manipulating Data, Commercial & Scientific Applications, Relational & Non-Relational Databases, Data Analytics, Cluster Computing, Dissertation Project
      - layout: left
        title: University of Stirling
        caption: 2014 - 2018
        sub_title: BSc Computing Science
        description: |
          Coursework: Software Engineering, Operating Systems Concurrency and Distribution, Information Systems, Computer Games Development, Computer Security and Networks Key Project: EPSRC-funded “AV-COGHEAR”

  - title: A Little More About Me
    layout: text
    content: |
      In my spare time, I love reading, learning new innovative technologies, and socializing with friends and family. Alongside my interests in data and software engineering some of my other interests and hobbies are:
      - Chess
      - Reading

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
